POST https://anjzle.com/mobile/orders/
Content-Type: application/json
Authorization: bearer ""

{
    "service_id": 15,
    "status_id": 1,
    "is_canceled": 0,
    "readed": 0,
    "content": "message",
    "user_readed": 1
}
